- name: Set master ip address
  set_fact: 
    master_ip_address: "{{ groups['masterNode'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"
  tags: swarm

- name: Remove service
  become: yes
  docker_swarm_service:
    name: myservice
    state: absent
  when: ansible_host == master_ip_address
  tags: swarm

- name: delete swarm
  become: yes
  shell: docker swarm leave --force
  tags: swarm

