# Create an instance on NeCTAR
- name: Create an instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: '{{ item.volumes }}'
    network: '{{ instance_network }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ instances }}'
  register: os_instance

- debug:
    msg: "Instance {{ item.openstack.name }} has been created. IP address is {{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

- name: Wait for connection
  wait_for:
    host: "{{ item.openstack.public_v4 }}"
    port: 22
    timeout: 120
    search_regex: OpenSSH
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

# Add hosts to Ansible in-memory inventory if groups['servers'] is not defined
- name: Add host
  add_host:
    hostname: '{{ item.openstack.public_v4 }}'
    groups: servers
    ansible_host: '{{ item.openstack.name }}'
  loop: '{{ os_instance.results }}'
  when: (groups["servers"]|length == 0) and item.openstack is defined

- name: Ensure hosts info is in inventory/inventory.ini
  lineinfile:
    path: inventory/inventory.ini
    line: '{{ item.openstack.name }} ansible_host={{ item.openstack.public_v4 }}'
    state: present
    insertafter: '\[servers\]'
    regexp: '^{{item.openstack.name}}'
  loop: '{{ os_instance.results }}'