- name: Set proxy to ~/.git_config
  git_config:
    name: http.proxy
    scope: global
    value: "{{ proxy_address }}"

- name: Clone the repo from Github
  git:
    repo: "{{ repo_address }}"
    dest: "{{ repo_local_path }}"
    update: yes
    clone: yes