- name: Set global git_config http.proxy
  git_config:
    name: http.proxy
    scope: global
    value: "{{ proxy_address }}"

- name: Set global git_config https.proxy
  git_config:
    name: https.proxy
    scope: global
    value: "{{ proxy_address }}"

- name: Clone the repo from Github
  git:
    repo: "{{ repo_address }}"
    dest: "{{ repo_local_path }}"
    update: yes
    clone: yes
    depth: "{{ repo_depth }}"