# Use for instances generation in nectar

- hosts: localhost
  vars_files:
    - variables/nectar.yaml
  gather_facts: true
  roles:
    - role: nectar-common
    - role: nectar-volume
    - role: nectar-security-group
    - role: nectar-instance