# Use for environment setup for all the managedNotes

- hosts: Nodes
  gather_facts: true
  vars_files:
    - variables/servers.yaml
  roles:
    - role: servers-proxy
    - role: servers-environment
    - role: servers-volume
    - role: servers-docker
    - role: servers-git
    - role: servers-restfulapi-server
    - role: servers-couchdb
      tags: test
