# Use for environment setup for all the managedNotes

- hosts: servers
  gather_facts: true
  roles:
    - role: servers-proxy
    - role: servers-environment
    - role: servers-volume
    # - role: servers-couchdb
