- hosts: localhost
  vars_files:
    - variables/nectar.yaml
  gather_facts: true
  roles:
    - role: test-delete-all
      tags: all-delete

- hosts: Nodes
  vars_files:
    - variables/servers.yaml
  roles:
    - role: test-clear-db
      tags: db-rebuild