# Common vars
availability_zone: melbourne-qh2-uom

# Volume
# Make sure the vol_name is the same as those in instances
volumes:
  - vol_name: vol_50_1
    vol_size: 50
  - vol_name: vol_50_2
    vol_size: 50

# Instance
# Include the information of their name and 
# and the volumes attached to them.
instances:
  - name: instance_1
    volumes: vol_50_1
  - name: instance_2
    volumes: vol_50_2

# Security group
security_groups:
  - name: ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: g17
instance_flavor: uom.mse.2c9g
instance_network: qh2-uom-internal

