# Common vars
availability_zone: melbourne-qh2-uom

# Volume
# Make sure the vol_name is the same as those in instances
volumes:
  - vol_name: vol_50_1
    vol_size: 50
  - vol_name: vol_50_2
    vol_size: 50
  - vol_name: vol_50_3
    vol_size: 50

# Instance
# Include the information of their name and 
# and the volumes attached to them.
instances:
  - name: instance_1
    volumes: vol_50_1
  - name: instance_2
    volumes: vol_50_2
  - name: instance_3
    volumes: vol_50_3

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: g17
instance_flavor: uom.mse.2c9g
instance_network: qh2-uom-internal

# Security group
security_groups:
  - name: ssh
    description: "Security group for SSH access"
    rules:
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0 
  - name: http
    description: "Security group for HTTP"
    rules:
      - protocol: tcp
        port_range_min: 80
        port_range_max: 80
        remote_ip_prefix: 0.0.0.0/0
  - name: swarm-required
    description: "Security group for swarm"
    rules:
      - protocol: tcp
        port_range_min: 2377
        port_range_max: 2377
        remote_ip_prefix: 0.0.0.0/0
      - protocol: tcp
        port_range_min: 4789
        port_range_max: 4789
        remote_ip_prefix: 0.0.0.0/0
      - protocol: tcp
        port_range_min: 5000
        port_range_max: 5000
        remote_ip_prefix: 0.0.0.0/0
  - name: couchdb-required
    description: "Security group for CouchDB HTTP communication"
    rules:
      - protocol: tcp
        port_range_min: 5984
        port_range_max: 5984
        remote_ip_prefix: 0.0.0.0/0
      - protocol: tcp
        port_range_min: 5986
        port_range_max: 5986
        remote_ip_prefix: 0.0.0.0/0 
      - protocol: tcp
        port_range_min: 4369
        port_range_max: 4369
        remote_ip_prefix: 0.0.0.0/0
      - protocol: tcp
        port_range_min: 8082
        port_range_max: 8082
        remote_ip_prefix: 0.0.0.0/0
      - protocol: tcp
        port_range_min: 9100
        port_range_max: 9200
        remote_ip_prefix: 0.0.0.0/0