- name: Set manager ip address
  tags: swarm-init
  set_fact: 
    master_ip_address: "{{ groups['masterNode'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"

- name:  Print the ip of manager
  tags: swarm-init
  debug: 
    msg: "manager ip: {{master_ip_address}}"


- name: Initialize Docker Swarm
  become: yes
  docker_swarm:
    state: present
    advertise_addr: "{{master_ip_address}}:2377"
  register: swarm_manager
  run_once: true
  tags: swarm-init

- name: Get info on Docker Swarm
  become: yes
  docker_swarm_info:
  ignore_errors: yes
  register: result
  tags: swarm-init

- name: Inform about basic flags
  debug:
    msg: |
      Was able to talk to docker daemon: {{ result.can_talk_to_docker }}
      Docker in Swarm mode: {{ result.docker_swarm_active }}
      This is a Manager node: {{ result.docker_swarm_manager }}
  tags: swarm-init

- name: Get the Manager join-token
  become: yes
  shell: docker swarm join-token --quiet manager
  when: result.docker_swarm_active == True
  register: manager_token
  tags: swarm-init

- name: Get the worker join-token
  become: yes
  shell: docker swarm join-token --quiet worker
  when: result.docker_swarm_active == True
  register: worker_token
  tags: swarm-init