# To allow these instances to be accessible externally.
- name: Add proxy in /etc/environment
  become: yes
  blockinfile:
    path: /etc/environment
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    block: |
      HTTP_PROXY={{ proxy_address }} 
      HTTPS_PROXY={{ proxy_address }}
      http_proxy={{ proxy_address }}
      https_proxy={{ proxy_address }}
      no_proxy={{ no_proxy_address }}

# Reboot to activate these proxy setting
- name: Reboot machines to activate proxy setting
  become: yes
  reboot:
    reboot_timeout: 600