# To allow these instances to be accessible externally.
- name: Add proxy in /etc/environment
  become: yes
  blockinfile:
    path: /etc/environment
    block: |
      HTTP_PROXY={{ proxy_address }} 
      HTTPS_PROXY={{ proxy_address }}
      http_proxy={{ proxy_address }}
      https_proxy={{ proxy_address }}
      no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.u nimelb.edu.au,.cloud.unimelb.edu.au

# Reboot to activate these proxy setting
- name: Reboot machines to activate proxy setting
  become: yes
  reboot:
    reboot_timeout: 600