# Install dependencies on the host
- name: Collect only facts returned by facter
  tags: localhostInit
  setup:
    gather_subset:
      - '!all'
      - '!all'
      - '!any'
      - facter

# sudo apt-get update; sudo apt-get install python-pip
- name: Install pip
  tags: localhostInit
  become: yes
  apt:
    name: ['python-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

# pip install --upgrade pip
- name: Update pip
  tags: localhostInit
  become: yes
  pip:
    name: ['pip']
    state: latest

# pip install openstacksdk
- name: Install openstacksdk
  tags: localhostInit
  become: yes
  pip:
    name: ['openstacksdk']
    state: latest