version: "3.7"

services:
    restful_api_server:
        build: ./server/restful_api_server
        container_name: restful_api_server
        restart: always
        environment:
            - APP_NAME=MyFlaskApp
        expose:
            - 3000
        volumes:
            - ./server/restful_api_server/config:/app/config
        
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "8080:80"
        expose:
            - 8080
        volumes:
            - ./client/dist:/dist