- name: initial docker manager
  hosts: masterNode
  gather_facts: true
  roles:
    - role: docker-swarm-init

- name: add workers
  hosts: slaveNode
  roles:
    - role: docker-swarm-addworker


- name: pull images and copy proxy config.json
  hosts: Nodes
  gather_facts: true
  roles:
    - role: docker-copy-proxyconfig
    - role: docker-pull-images

- name: deploy services 
  hosts: masterNode
  gather_facts: true
  roles:
    - role: docker-swarm-service