- name: Download Couchbase package
  get_url: 
    url: http://packages.couchbase.com/releases/2.0.1/couchbase-server-enterprise_x86_64_2.0.1.deb 
    dest: ~/.

- name: Install dependencies
  become: yes
  apt: 
    pkg: libssl 
    state: latest

- name: Install Couchbase .deb file on all machines
  shell: dpkg -i ~/couchbase-server-enterprise_x86_64_2.0.1.deb