- name: Collect facts of the host
  tags: couchdb
  setup:
    gather_subset:
      - '!any'

- name: Set master ip address
  tags: couchdb
  set_fact: 
    master_ip_address: "{{ groups['masterNode'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"

- name:  Print the ip of master
  tags: couchdb
  debug: 
    msg: "Master ip: {{master_ip_address}}"

- name: Get the size of cluster
  tags: couchdb
  set_fact:
    cluster_size: "{{ groups['Nodes'] | length }}"    
    
- name: Print the size of cluster
  debug:
    msg: "Size of cluster: {{ cluster_size }} "

- name: Create couchDB working directory
  tags: couchdb
  become: yes
  file:
    path: "{{ couchDB_dir }}"
    recurse: yes
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create couchDB data directory
  tags: couchdb
  become: yes
  file:
    path: "{{ couchDB_data_dir }}"
    recurse: yes
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: "Copy couchDB vm.args to {{ couchDB_dir }}"
  become: yes
  template:
    src: vm.args.j2
    dest: '{{ couchDB_dir }}/vm.args'
    force: no
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: "Copy docker-compose.yaml to {{ couchDB_dir }}"
  become: yes
  copy:
    src: Dockerfile
    dest: "{{ couchDB_dir }}/Dockerfile"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create couchDB docker-compose
  tags: couchdb
  become: yes
  template:
    src: docker-compose.yaml.j2
    dest: "{{ couchDB_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run couchDB docker-compose
  tags: couchdb
  become: yes
  docker_compose:
    project_src: "{{ couchDB_dir }}"
    pull: yes
    remove_orphans: yes
    state: present
    recreate: always

- name: "Copy masterSetUp.sh to {{ couchDB_dir }}"
  tags: couchdb
  become: yes
  template:
    src: clusterSetUp.sh.j2
    dest: "{{ couchDB_dir }}/clusterSetUp.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '777'

- name: Cluster init
  tags: couchdb
  become: yes
  shell: "{{ couchDB_dir }}/clusterSetUp.sh  >> {{ couchDB_dir }}/log_clusterSetUp.sh"

- name: "Copy addToMaster.sh to {{ couchDB_dir }}"
  tags: couchdb
  become: yes
  template:
    src: addToMaster.sh.j2
    dest: "{{ couchDB_dir }}/addToMaster.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '777'
  when: ansible_host != master_ip_address

- name: Add slave Node to cluster
  tags: couchdb
  become: yes
  shell: "{{ couchDB_dir }}/addToMaster.sh  >> {{ couchDB_dir }}/log_addToMaster.txt"
  when: ansible_host != master_ip_address