- name: Collect facts of the host
  tags: couchdb
  setup:
    gather_subset:
      - '!any'

- name: Set master ip address
  tags: couchdb
  set_fact: 
    master_ip_address: "{{ groups['masterNode'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"

- name:  Print the ip of master
  tags: couchdb
  debug: 
    msg: "Master ip: {{master_ip_address}}"

- name: Get the size of cluster
  tags: couchdb
  set_fact:
    cluster_size: "{{ groups['Nodes'] | length }}"    
    
- name: Print the size of cluster
  debug:
    msg: "Size of cluster: {{ cluster_size }} "

- name: Create couchDB working directory
  tags: couchdb
  become: yes
  file:
    path: "{{ couchDB_dir }}"
    recurse: yes
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create couchDB data directory
  tags: couchdb
  become: yes
  file:
    path: "{{ couchDB_data_dir }}"
    recurse: yes
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: "Copy couchDB vm.args to {{ couchDB_dir }}"
  become: yes
  template:
    src: vm.args.j2
    dest: '{{ couchDB_dir }}/vm.args'
    force: no
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: "Copy docker-compose.yaml to {{ couchDB_dir }}"
  become: yes
  copy:
    src: Dockerfile
    dest: "{{ couchDB_dir }}/Dockerfile"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create couchDB docker-compose
  tags: couchdb
  become: yes
  template:
    src: docker-compose.yaml.j2
    dest: "{{ couchDB_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run couchDB docker-compose
  tags: couchdb
  become: yes
  docker_compose:
    project_src: "{{ couchDB_dir }}"
    pull: yes
    remove_orphans: yes
    state: present
    recreate: always

# curl -X POST -H "Content-Type: application/json" http://admin:password@127.0.0.1:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"password", "node_count":"3"}'
- name: "Copy masterSetUp.sh to {{ couchDB_dir }}"
  tags: couchdb
  become: yes
  template:
    src: clusterSetUp.sh.j2
    dest: "{{ couchDB_dir }}/clusterSetUp.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '777'

- name: Cluster init
  tags: couchdb
  become: yes
  shell: "{{ couchDB_dir }}/clusterSetUp.sh  >> {{ couchDB_dir }}/log_clusterSetUp.txt"

# curl -X POST -H "Content-Type: application/json" http://admin:password@<setup-coordination-node>:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"password", "port": 5984, "node_count": "3", "remote_node": "<remote-node-ip>", "remote_current_user": "<remote-node-username>", "remote_current_password": "<remote-node-password>" }'
# curl -X POST -H "Content-Type: application/json" http://admin:password@<setup-coordination-node>:5984/_cluster_setup -d '{"action": "add_node", "host":"<remote-node-ip>", "port": <remote-node-port>, "username": "admin", "password":"password"}'
- name: "Copy addToMaster.sh to {{ couchDB_dir }}"
  tags: couchdb
  become: yes
  template:
    src: addToMaster.sh.j2
    dest: "{{ couchDB_dir }}/addToMaster.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '777'
  when: ansible_host != master_ip_address

- name: Add slave Node to cluster
  tags: couchdb
  become: yes
  shell: "{{ couchDB_dir }}/addToMaster.sh  >> {{ couchDB_dir }}/log_addToMaster.txt"
  when: ansible_host != master_ip_address

# curl -X POST -H "Content-Type: application/json" http://cccg17:cccg17@172.26.133.180:5984/_cluster_setup -d '{"action": "finish_cluster"}'
- name: "Copy completeClusterSetUp.sh to {{ couchDB_dir }}"
  tags: couchdb
  become: yes
  template:
    src: completeClusterSetUp.sh.j2
    dest: "{{ couchDB_dir }}/completeClusterSetUp.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '777'
  when: ansible_host == master_ip_address

- name: Complete cluster setting!
  tags: couchdb
  become: yes
  shell: "{{ couchDB_dir }}/completeClusterSetUp.sh  >> {{ couchDB_dir }}/log_completeClusterSetUp.txt"
  when: ansible_host == master_ip_address

# Verify install:
# curl http://cccg17:cccg17@172.26.133.180:5984/_cluster_setup
# Respect response: {"state":"cluster_finished"}
#
# Verify all cluster nodes are connected:
# curl http://cccg17:cccg17@172.26.133.180:5984/_membership